export const CLEAR_CHARACTERS = "CLEAR_CHARACTERS";
export const GET_CHARACTER_SUCCESS = "GET_CHARACTER_SUCCESS";
export const GET_CHARACTERS_SUCCESS = "GET_CHARACTERS_SUCCESS";
export const UPDATE_FAVORITE_SUCCESS = "UPDATE_FAVORITE_SUCCESS";
export const TOKEN_EXPIRED = "TOKEN_EXPIRED";
